kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./build/ray.Dockerfile
  context: .

spec:
  operator: kuberay
  image: image
  command: "python3 -u main.py --operator=kuberay --sleep=120 --tb-write=false"

  debug:
    jupyter: false

  tensorboard:
    enabled: false

  types:
    Head:
      resources:
        cpus: 3
        ramRatio: 2
        accelerators: # optional
          gpu:
            count: 1
            type: gpu
            product: T4
    Workers:
      - name: cpu-workers
        count: 1
        resources:
          cpus: 3
          ramRatio: 2
          shmSizeGB: 0
          accelerators: # optional
            gpu:
              count: 1
              type: gpu
              product: T4
